### ISSUE TITLE
Update README.md to reflect how to cite (once discussion is final)

### ISSUE THREAD

**Issue by ghost** [MobleyLab/benchmarksets#61]

**Comment by davidlmobley** [comment]
Great question. I need to add an explicit note of this to the main README.md since this will be a common question; I'll update the title of the issue to reflect that.

Ideally, you would cite a couple of items:
a) Our Annual Reviews paper (the original)
b) The specific version you are using, as posted on eScholarship (permanent URL: https://escholarship.org/uc/item/9p37m6bq ; all versions available there)
c) Give a link to the GitHub repo in your paper

I think the combination of the three would be ideal. Thoughts, @mkgilson , @nhenriksen , @GHeinzelmann ? Once we agree, I'll update the repo to reflect. :) 

Thanks.

**Comment by GHeinzelmann** [comment]
Sound good to me, let me know if I can help in any way,

**Comment by davidlmobley** [comment]
Discussed with Gilson, who suggests:

> Certainly cite the Ann Rev article.  What if we simplify the citation to updated versions by requesting a second citation to the current escholarship version, and including a link to the github site from the escholarship version? This will avoid the need to provide three citations...

I agree, and there is already a link at eScholarship to GitHub (though I need to fix it so it's a hyperlink). 

I'll try and do this today.

**Comment by davidlmobley** [comment]
I just added this to the main README.md. Thanks.
